### ISSUE TITLE
testsuite is broken (since datasette 0.54)

### ISSUE THREAD

**Issue by mfa** [mfa/meinsack-datasette#2]
```
Traceback (most recent call last):
  File "/home/mfa/.virtualenv/meinsack-datasette/lib/python3.9/site-packages/datasette/app.py", line 1125, in route_path
    response = await view(request, send)
  File "/home/mfa/.virtualenv/meinsack-datasette/lib/python3.9/site-packages/datasette/views/base.py", line 146, in view
    return await self.dispatch_request(                                                                                                                                                                             
  File "/home/mfa/.virtualenv/meinsack-datasette/lib/python3.9/site-packages/datasette/views/base.py", line 119, in dispatch_request
    await self.ds.refresh_schemas()                                                                       
  File "/home/mfa/.virtualenv/meinsack-datasette/lib/python3.9/site-packages/datasette/app.py", line 348, in refresh_schemas
    await internal_db.execute_write(
  File "/home/mfa/.virtualenv/meinsack-datasette/lib/python3.9/site-packages/datasette/database.py", line 102, in execute_write
    return await self.execute_write_fn(_inner, block=block)
  File "/home/mfa/.virtualenv/meinsack-datasette/lib/python3.9/site-packages/datasette/database.py", line 118, in execute_write_fn
    raise result
  File "/home/mfa/.virtualenv/meinsack-datasette/lib/python3.9/site-packages/datasette/database.py", line 139, in _execute_writes
    result = task.fn(conn)
  File "/home/mfa/.virtualenv/meinsack-datasette/lib/python3.9/site-packages/datasette/database.py", line 100, in _inner
    return conn.execute(sql, params or [])
sqlite3.InterfaceError: Error binding parameter 1 - probably unsupported type.
```

this is maybe related to the race condition @simonw mentions in simonw/datasette#1231

for testrun see: https://github.com/mfa/meinsack-datasette/runs/2301260026

**Comment by mfa** [comment]
My testsuite runs fine with this change in https://github.com/simonw/datasette/

```
diff --git a/datasette/app.py b/datasette/app.py
index ee81642..d57d689 100644
--- a/datasette/app.py
+++ b/datasette/app.py
@@ -329,6 +329,9 @@ class Datasette:
         self.client = DatasetteClient(self)
 
     async def refresh_schemas(self):
+        if True:
+            return
+
         internal_db = self.databases["_internal"]
         if not self.internal_db_created:
             await init_internal_db(internal_db)

```

**Comment by mfa** [comment]
The proposed change in simonw/datasette#1231 didn't help.

**Comment by mfa** [comment]
tests run fine with datasette==0.53 and break with the introduction of `_internal` database (datasette 0.54)

**Comment by mfa** [comment]
with pdb activated (and datasette 0.56):
```
Error binding parameter 1 - probably unsupported type.
> /home/mfa/.virtualenv/meinsack-datasette/lib/python3.9/site-packages/datasette/database.py(100)_inner()
-> return conn.execute(sql, params or [])
(Pdb) sql
'\n                INSERT OR REPLACE INTO databases (database_name, path, is_memory, schema_version)\n                VALUES (?, ?, ?, ?)\n            '
(Pdb) params
['meinsack', PosixPath('/home/mfa/git/meinsack-datasette/meinsack.db'), False, 35]
```

**Comment by mfa** [comment]
fixed by casting `PosixPath` to `str`
